# Site settings
title: GUANGHUIZ
email: ""
description: "Know all about me from here."
baseurl: ""
# url: "http://www.guanghuiz.com"
github_username:  kensupernova
# Build settings
markdown: kramdown
permalink: pretty

# time zone
timezone: Asia/Singapore
encoding: utf-8
