# Site settings
title: Guanghui Zhang
email: ghzhang66 at gmail
description: "Know all about me from here."
baseurl: ""
# url: "http://www.guanghuiz.com"
twitter_username: kensupernova
github_username:  kensupernova
# Build settings
markdown: kramdown
permalink: pretty

# time zone
timezone: Asia/Singapore
encoding: utf-8

#nav config
nav:
  - text: Home
    url: /
  - text: Category
    url: /categories/
  - text: Archive
    url: /archives/
  - text: Link
    url: /links/
  - text: Contact
    url: /contact/
  # - text: About
  #   url: /about/

# comment config
disqus:
  config: false
  id: guanghuiz

duoshuo:
  config: true
  id: kensupernova
